#!/bin/bash
set -e; set -o pipefail

function build_zbuild()
{
	scripts/check_build_env.sh
	go build -o zbuild tools/zbuild/*.go
	# Force rebuild.
	touch zeptux.zbuild
}

function zbuild_up_to_date()
{
	for file in tools/zbuild/*.go; do
		if [[ $file -nt zbuild ]]; then
		   return 1
		fi
	done
}

if ! [[ -e zbuild ]] || ! zbuild_up_to_date; then
	build_zbuild
fi

./zbuild $@
